### ISSUE TITLE
Youtube API key leak

### ISSUE THREAD

**Issue by xXBuilderBXx** [BlackScarx/DiscordMusicPlayer#1]
You have a token leak here https://github.com/BlackScarx/DiscordMusicPlayer/blob/master/src/main/java/net/blackscarx/discordmusicplayer/DiscordManager.java#L126
https://i.imgur.com/XTiF9NT.png

**Comment by ohlookitsderpy** [comment]
mmLol

**Comment by BlackScarx** [comment]
Search for youtube video without API Key

**Comment by m4cul** [comment]
Any impact for youtube api key leak?

**Comment by Benjamin-Loison** [comment]
> Search for youtube video without API Key

@BlackScarx 

Maybe using a reverse-engineer approach of YouTube UI as I partially did in my [open-source](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/ca5f9979391376eeb60c907254b244d6ce03762f/search.php#L105-L117) [YouTube operational API](https://yt.lemnoslife.com) would make sense. You can test my code by reaching https://yt.lemnoslife.com/search?part=id,snippet&q=YOUR_QUERY

Otherwise you could rely on personal YouTube Data API v3 key instead of exposing it, or using my no-key service is more resilient than using a single leaked hardcoded YouTube Data API v3 key, you can give it a try by reaching https://yt.lemnoslife.com/noKey/search?part=id,snippet&q=YOUR_QUERY&type=video. Note that there is currently [an issue with using `filters` with my no-key service](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/27).

**Comment by BlackScarx** [comment]
I removed the api key from the code and add a settings to add your own one for the youtube search feature
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.5.0

**Comment by xXBuilderBXx** [comment]
I feel 7 years younger looking at this 🙃
